name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write' # Required for Workload Identity Federation

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          workload_identity_provider: 'projects/722595657772/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-repo-provider'
          service_account: '${{ secrets.DEPLOYMENT_SA_EMAIL }}'

      - name: Authenticate Docker to Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Frontend
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/frontend:${{ github.sha }} -f gcp-security-hardener3/frontend/Dockerfile.frontend gcp-security-hardener3/frontend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/frontend:${{ github.sha }}

      - name: Build and Push Backend
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/backend:${{ github.sha }} -f gcp-security-hardener3/backend/Dockerfile.backend gcp-security-hardener3/backend
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/backend:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: ./terraform/application
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform/application
        run: terraform plan -out=tfplan
        env:
          TF_VAR_frontend_image: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/frontend:${{ github.sha }}'
          TF_VAR_backend_image: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/backend:${{ github.sha }}'
          TF_VAR_iap_client_id: '${{ secrets.IAP_CLIENT_ID }}'
          TF_VAR_iap_client_secret: '${{ secrets.IAP_CLIENT_SECRET }}'

      - name: Terraform Apply
        working-directory: ./terraform/application
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_frontend_image: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/frontend:${{ github.sha }}'
          TF_VAR_backend_image: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/repo/backend:${{ github.sha }}'
          TF_VAR_iap_client_id: '${{ secrets.IAP_CLIENT_ID }}'
          TF_VAR_iap_client_secret: '${{ secrets.IAP_CLIENT_SECRET }}'
